# Generated by Django 4.1.3 on 2022-12-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('address', models.BigIntegerField()),
                ('food_details', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
